/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SheetAbilities: typeof import('./components/SheetAbilities.vue')['default']
    SheetHabilities: typeof import('./components/SheetHabilities.vue')['default']
    SheetInventory: typeof import('./components/SheetInventory.vue')['default']
    SheetOverview: typeof import('./components/SheetOverview.vue')['default']
    SheetTalent: typeof import('./components/SheetTalent.vue')['default']
    SheetWrapper: typeof import('./components/SheetWrapper.vue')['default']
  }
}
